#fileformat example: p1_amae.txt
import os
import re
import numpy as np
import pandas as pd

import csv
df = pd.read_csv('eGeMAPSv01b_acoustics_dutchFemales.csv')

# updating the column value/data
df['Emotion_Category'] = df['Emotion_Category'].replace({'admiration':'admiration'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'amae':'amae'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'amusement':'amusement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'amusementwav':'amusement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'amusment':'amusement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'amusemet':'amusement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'amusem':'amusement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'laugh':'amusement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'awe':'awe'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'determination':'determination'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'determinatino':'determination'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'elation':'elation'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'elat':'elation'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'la':'elation'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'euphoria':'elation'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'elevation':'elevation'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'excitement':'excitement'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'gratitude':'gratitude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'hope':'hope'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'inspiration':'inspiration'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'interest':'interest'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'fascinatie':'interest'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'interested':'interest'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'lust':'lust'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'moved':'moved'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'mo':'moved'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'positivesurprise':'positivesurprise'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'positivesuprise':'positivesurprise'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'possurprise':'positivesurprise'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'possuprise':'positivesurprise'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'pride':'pride'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'relief':'relief'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'respected':'respected'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'respec':'respected'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'schanfreude':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'schadenfreude':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'schadenfrude':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'schanfruede':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'malaciousjoy':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'maliciousjoy':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'malicious':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'malicioursjoy':'schadenfreude'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'senspleasure':'sensualpleasure'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'sensualpleasure':'sensualpleasure'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'sensualpleasure':'sensualpleasure'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'senspleas':'sensualpleasure'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'tenderness':'tenderness'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'tederness':'tenderness'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'triumph':'triumph'})
df['Emotion_Category'] = df['Emotion_Category'].replace({'triu':'triumph'})

print(df)

df.to_csv(r'C:\Users\jesus\Desktop\AMSTERDAM\psychology\Feature-Extraction\opensmile-3.0-win-x64\opensmile-3.0-win-x64\example-audio\eGeMAPSv01b_acoustic_dutchFemales.csv', index = False)

